name: Update lotr.json

on:
  push:
    branches:
      - main  # ou la branche que tu utilises pour déclencher le workflow

jobs:
  update-lotr-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update lotr.json
        run: |
          curl -X PUT -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
               -d @lotr.json \
               https://api.github.com/repos/gaspyyyyyy6/Lotr/contents/lotr.json
