name: Mettre à jour LotR Data

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le repo
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Mettre à jour le fichier lotr.json
        env:
          TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          curl -X PUT -H "Authorization: token $TOKEN" \
          -H "Content-Type: application/json" \
          -d @lotr.json \
          https://api.github.com/repos/gaspyyyyyy6/Lotr/contents/lotr.json

      - name: Commit et push des modifications
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add lotr.json
          git commit -m "Mise à jour automatique du fichier lotr.json"
          git push https://x-access-token:${TOKEN}@github.com/gaspyyyyyy6/Lotr.git
